name: Validate Blueprint catalog content

on:
  workflow_call:
    secrets:
      api-token:
        required: true

env:
  CATALOG_FILE: .blueprint/catalog-info.yaml

jobs:
  validate:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    env:
      BLUEPRINT_BASE_URL: ${{ vars.BLUEPRINT_BASE_URL }}
      BLUEPRINT_API_TOKEN: ${{ secrets.api-token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if ${{ env.CATALOG_FILE }} has changed
        id: file-check
        run: |
          echo "Checking for changes in ${{ env.CATALOG_FILE }}"
          git fetch origin ${{ github.event.before }}
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "${{ env.CATALOG_FILE }}"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Validate ${{ env.CATALOG_FILE }}
        if: steps.file-check.outputs.changed == 'true'
        run: |
          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's|refs/heads/||')
  
          awk 'BEGIN{n=0;} /^---/{n++} {print > ("entity_" n ".yaml")}' "${{ env.CATALOG_FILE }}"
          for entity in entity_*.yaml; do
            KIND=$(cat "$entity" | yq '.kind')
            NAME=$(cat "$entity" | yq '.metadata.name')
            echo "--- Validating $KIND:$NAME"
            json=$(yq -o=json "$entity")
            response=$(curl -s -w "%{http_code}" -o response.json -X POST "$BLUEPRINT_BASE_URL/api/catalog/validate-entity" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $BLUEPRINT_API_TOKEN" \
              -d "{\"location\": \"url:https://github.com/$ORG_NAME/$REPO_NAME/blob/$BRANCH_NAME/${{ env.CATALOG_FILE }}\", \"entity\": $json}")
          
            status_code="${response: -3}"
            body=$(cat response.json)
            if [ "$status_code" -ne 200 ]; then
              cat "$entity"
              echo "$body"
              echo "❌ Validation failed with status code $status_code"
              exit 1
            fi
          done
