name: Test YAML Validation Workflow

on:
  push:
  pull_request:

jobs:
  blueprint:
    uses: ./.github/workflows/blueprint-validate.yaml
    secrets:
      BACKSTAGE_BASE_URL: ${{ secrets.BACKSTAGE_BASE_URL }}
      BACKSTAGE_API_TOKEN: ${{ secrets.BACKSTAGE_API_TOKEN }}

